In [18]:
import pandas as pd
from rouge_score import rouge_scorer

ds_df = pd.read_csv("deepSeekFINAL.csv")
ll_df = pd.read_csv("llamaPromptedSummaries.csv")

In [19]:
## Compute Rouge for DeepSeek
scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)

r1, r2, rL = [], [], []

for s1, s2 in zip(ds_df['summaries'], ds_df['generated_summary']):
    score = scorer.score(str(s1),str(s2))

    r1.append(score['rouge1'].fmeasure)
    r2.append(score['rouge2'].fmeasure)
    rL.append(score['rougeL'].fmeasure)

ds_df['rouge1'] = r1
ds_df['rouge2'] = r2
ds_df['rougeL'] = rL

In [25]:
## Compute Rouge for llama
scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)

r1, r2, rL = [], [], []

for s1, s2 in zip(ll_df['summaries'], ll_df['prompted_summary']):
    score = scorer.score(str(s1),str(s2))

    r1.append(score['rouge1'].fmeasure)
    r2.append(score['rouge2'].fmeasure)
    rL.append(score['rougeL'].fmeasure)

ll_df['rouge1'] = r1
ll_df['rouge2'] = r2
ll_df['rougeL'] = rL

In [ ]:
ds_results = ds_df[['movie_id', 'rouge1', 'rouge2', 'rougeL']]
ds_results.sort_values('rouge1', ascending=False).head(5)

     movie_id    rouge1    rouge2    rougeL
267   9503643  0.550523  0.155995  0.204413
149   9506982  0.534819  0.175978  0.236769
36    9221113  0.533808  0.175000  0.263345
115   9286226  0.532775  0.145455  0.239888
73    9403636  0.532526  0.133536  0.226929

In [21]:
ds_results.sort_values('rouge2', ascending=False).head(5)

     movie_id    rouge1    rouge2    rougeL
149   9506982  0.533333  0.189415  0.252778
231   9376852  0.527660  0.149573  0.229787
157   9212873  0.421365  0.137313  0.225519
73    9403636  0.452703  0.125424  0.195946
347   9489880  0.366581  0.124680  0.168798

In [22]:
ds_results.sort_values('rougeL', ascending=False).head(5)

     movie_id    rouge1    rouge2    rougeL
149   9506982  0.533333  0.189415  0.252778
210   9263407  0.421053  0.095238  0.236842
36    9221113  0.455696  0.119782  0.235081
263   9264457  0.387597  0.085938  0.232558
296   9200491  0.371901  0.091667  0.231405

In [27]:
ll_results = ll_df[['movie_id', 'rouge1', 'rouge2', 'rougeL']]
ll_results.sort_values('rouge1', ascending=False).head(5)

     movie_id    rouge1    rouge2    rougeL
267   9503643  0.550523  0.155995  0.204413
149   9506982  0.534819  0.175978  0.236769
36    9221113  0.533808  0.175000  0.263345
115   9286226  0.532775  0.145455  0.239888
73    9403636  0.532526  0.133536  0.226929

In [30]:
ll_results = ll_df[['movie_id', 'rouge1', 'rouge2', 'rougeL']]
ll_results.sort_values('rouge2', ascending=False).head(5)

     movie_id    rouge1    rouge2    rougeL
149   9506982  0.534819  0.175978  0.236769
36    9221113  0.533808  0.175000  0.263345
77    9242689  0.469799  0.168161  0.230425
122   9512869  0.429947  0.160772  0.233155
327   9489767  0.467440  0.159071  0.206958

In [29]:
ll_results = ll_df[['movie_id', 'rouge1', 'rouge2', 'rougeL']]
ll_results.sort_values('rougeL', ascending=False).head(5)

     movie_id    rouge1    rouge2    rougeL
36    9221113  0.533808  0.175000  0.263345
8     9507853  0.380488  0.117647  0.253659
100   9470963  0.449649  0.131765  0.252927
115   9286226  0.532775  0.145455  0.239888
149   9506982  0.534819  0.175978  0.236769